# Generated by Django 3.2.2 on 2021-10-13 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationGroupNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CombinationGrouperChangers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planetName', models.CharField(max_length=100)),
                ('planetChangedName', models.CharField(max_length=100)),
                ('groupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiples.combinationgroupnames')),
            ],
        ),
    ]
