# Generated by Django 3.2.2 on 2021-10-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLis', models.TextField(max_length=2000)),
                ('m1ChartName', models.CharField(max_length=100)),
                ('birthTime', models.CharField(max_length=100)),
                ('p1Place', models.CharField(max_length=100)),
                ('p2Place', models.CharField(max_length=100)),
            ],
        ),
    ]
