# Generated by Django 3.2.2 on 2021-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiples', '0002_model1charts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLis', models.TextField(max_length=2000)),
                ('m2ChartName', models.CharField(max_length=100)),
                ('p1Time', models.CharField(max_length=100)),
                ('p1Place', models.CharField(max_length=100)),
                ('fName', models.CharField(max_length=100)),
                ('p2Date', models.CharField(max_length=100)),
                ('p2Time', models.CharField(max_length=100)),
                ('p2Place', models.CharField(max_length=100)),
            ],
        ),
    ]
