# Generated by Django 3.2.2 on 2021-11-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiples', '0006_trendchart2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendChart3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartName', models.CharField(max_length=100)),
                ('dateLis', models.CharField(max_length=100)),
                ('combinations', models.CharField(max_length=100)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
            ],
        ),
    ]
