# Generated by Django 3.2.7 on 2021-10-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetGroupNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetGroupers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planetChangedName', models.CharField(max_length=100)),
                ('planetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlpanel.planetgroupnames')),
            ],
        ),
    ]
