# Generated by Django 3.2.7 on 2021-10-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0002_planetgroupers_planetgroupnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetgroupers',
            name='groupName',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='controlpanel.planetgroupnames'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planetgroupers',
            name='planetName',
            field=models.CharField(max_length=100),
        ),
    ]
